export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_RESPONSE = 'SIGN_UP_RESPONSE';
export const LOGIN = 'LOGIN';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const NO_TOKEN_FOUND = 'NO_TOKEN_FOUND';
export const RESUME_SESSION = 'RESUME_SESSION';
export const RESUME_SESSION_RESPONSE = 'RESUME_SESSION_RESPONSE';
export const LOGOUT = 'LOGOUT';